# .github/workflows/peakperformr-api-AutoDeployTrigger-e8e0a6cf-7ac1-4946-b247-4d0ba56b04ed.yml
name: Trigger auto deployment for peakperformr-api
on:
  # Trigger only on changes within the 'plumber' directory or the workflow file itself
  push:
    branches:
      [ master ]
    paths:
      - 'plumber/**' # Corrected: Only watch the API code directory
      - '.github/workflows/peakperformr-api-AutoDeployTrigger-e8e0a6cf-7ac1-4946-b247-4d0ba56b04ed.yml'
  # Allow manual trigger
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC Azure Login
      contents: read  # Required for checkout
      packages: write # Required for pushing to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated version
      
      - name: Verify repository structure
        run: |
          echo "Repository structure:"
          find plumber -type f | sort
          echo "Contents of plumber directory:"
          ls -la plumber
          echo "Contents of data directory:"
          ls -la plumber/data || echo "Data directory not found or empty"
          echo "Checking Dockerfile:"
          cat plumber/Dockerfile
      
      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PEAKPERFORMRAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PEAKPERFORMRAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PEAKPERFORMRAPI_AZURE_SUBSCRIPTION_ID }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.PEAKPERFORMRAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.PEAKPERFORMRAPI_REGISTRY_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: plumber
          file: plumber/Dockerfile
          push: true
          tags: ghcr.io/elivatsaas/peakperformr/plumber-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: peakperformr-api
          resourceGroup: NAUFLG-asc-export
          imageToDeploy: ghcr.io/elivatsaas/peakperformr/plumber-api:${{ github.sha }}
          # Skip build part - we already built and pushed the image
          skipBuild: true
